### ISSUE TITLE
No Vcenter

### ISSUE THREAD

**Issue by gunner4361** [ANSSI-FR/DFIR4vSphere#2]
Can this DFIR4vSphere be used to collect aginst a single ESXi host with no vcenter?

In a lot of cases the TA kills VC

**Comment by ldap389** [comment]
Hello Gunner,

No DFIR4vSphere does not run against a single ESXi. 

And yes in a ransomware case, the TA kills  the VC, good point. But it additionally reset local root ESXi accounts. So you cannot access a single ESXi host. Your only chance is to restore the vCenter from backup, compromised ESXi will then re-attach automatically to the vCenter and then launch DFIR4vSphere. To access again the compromised ESXi with local accounts you can perform a password reset through vCenter API calls (here is a script to perform the action https://www.hypervisor.fr/?p=5655)

Hope this answer your issue

**Comment by ldap389** [comment]
See answer above, no feedback closing. Adding comment in README
