### ISSUE TITLE
Truncated JSON output

### ISSUE THREAD

**Issue by anotherjarvi** [ANSSI-FR/DFIR4vSphere#3]
I'm receiving a warning:

'WARNING: Resulting JSON is truncated as serialization has exceeded the set depth of 5.'

when running Start-VC_Investigation.  Is it possible to create a '-Depth' parameter for this?

Thanks,
Steve

**Comment by EmilienCourt** [comment]
Hi @anotherjarvi,

Sorry for the delay.

I have actually increased the Depth to 99, which should fix the issue.

Please feel free to re-open an issue if this does not fix your issue :)
